### ISSUE TITLE
docker version update to support multi stage builds

### ISSUE THREAD

**Issue by zetaron** [heptio/aws-quickstart#107]
Hey I've recently started to enjoy the heptio quickstart.
So far it's been quite the awesome and easy to use, providing exactly what I've expected! 

Today I setup a Jenkins to shift some of our docker build and software CI into kubernetes. 
Sadly the installed docker version does not support the multi stage build feature which we use quite a lot. As it allows us to encapsulate the whole build, test and release artifact in one simple step.

Would you be interested in updating or is there a particular reason to stick with the current one? 
If you're open to upgrading I'll try to help, though I haven't done any AMI development yet.

**Comment by timothysc** [comment]
@zetaron we track upstream versions that are fully vetted.  Are you building on your cluster, or can you build externally?

**Comment by craigtracey** [comment]
Kubernetes 1.8 is currently only tested against 1.11.2, 1.12.6, 1.13.1, and 17.03.2 (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md#external-dependencies). Multi-stage builds are not available until 17.05, unfortunately.

Care should be exercised when building Docker images in this manner, as all of the paths require some level of escalated privileges.

**Comment by zetaron** [comment]
@timothysc I wanted to build on the cluster for simplicity but could build externally which would somewhat overcomplicate things, I think will just go with not using multistage builds for now.

@craigtracey Oh I did not know that Kubernetes is currently not tested against 17.05, will keep an eye on it.

**Comment by timothysc** [comment]
@craigtracey we should eval your recent updates.

**Comment by timothysc** [comment]
Going to close this.  We will match what are the supported versions by upstream.
