### ISSUE TITLE
kubelet on nodes spits useless errors

### ISSUE THREAD

**Issue by chuckha** [heptio/aws-quickstart#117]
our node kubelets are configured with `--manifest-path` (or whatever it is) and they spew this useless error

`Dec 15 18:28:36 ip-10-0-26-239 kubelet[1129]: E1215 18:28:36.106590    1129 file.go:76] Unable to read manifest path "/etc/kubernetes/manifests": path does not exist, ignoring`

we can either create that dir so the error goes away or not set the static manifest path on the *node* kubelet (not the master)

**Comment by timothysc** [comment]
Evaluate if this goes away when we use wardroom with standard packages which should create the directories.

**Comment by chuckha** [comment]
This is now beautifully quiet.
