### ISSUE TITLE
Create simplified punch-list for release.

### ISSUE THREAD

**Issue by timothysc** [heptio/aws-quickstart#130]
Make it so easy anyone can do it, and try to have @liztio go through the process.

**Comment by timothysc** [comment]
Document the process is the only final changes.

**Comment by liztio** [comment]
note for monday-liz:

1. Build new AMIs using wardroom
2. PR new AMIs
3. Boot a quickstart from the PR branch using the manual instructions
4. If it succeeds, merge PR
5. PR to aws-quickstart/quickstart-heptio:develop
