### ISSUE TITLE
Issue with deleting StatefulSets (sts) 

### ISSUE THREAD

**Issue by gmflau** [heptio/aws-quickstart#146]
I deployed a K8 cluster using Heptio's AWS-QS.  I was also able to deploy my Statefulset.  However, I got the following error when trying to delete my Statefulset.

$ kubectl get statefulset dse -o wide
NAME      KIND
dse       StatefulSet.v1.apps
$ kubectl delete statefulset dse
error: no kind "GetOptions" is registered for version "apps/v1"

**Comment by craigtracey** [comment]
Thanks for the report @gmflau.  This appears to be a problem with your `kubectl` client.  Could you provide the output from `kubectl version`?

**Comment by gmflau** [comment]
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by craigtracey** [comment]
@gmflau assuming that you are using out latest release of aws-quickstart, the server version would be 1.9.2.  You can verify this with the same `kubectl version` command, as it will list the server version as well.  There is componentry in the client that will need to match the server version.  Could you please retry your actions with the `kubectl` that matches your aws-quickstart version?

**Comment by gmflau** [comment]
Thanks Craig.  Confirmed it was the issue of my kubectl CLI client.  It has to be 1.9.x or higher to work.
