### ISSUE TITLE
Dashboard should be pinned to master node

### ISSUE THREAD

**Issue by jbeda** [heptio/aws-quickstart#158]
Right now the dashboard tolerates the master node but isn't pinned to it.  We should add a host constraint to ensure the dashboard only runs on that node.

Why?
* Typically the dashboard starts up fast enough it almost always lands on the master node.
* We have a network policy preventing all access to the dashboard
* Network policy doesn't apply when traffic comes from the host (to support health checks from the kubelet)
* `kubectl proxy` goes through the API server on the master node.

This means that `kubectl proxy` for the dashboard works most of the time because of the same node behavior of network policy.  If the dashboard is upgraded or modified in any way a new pod is created and it will most likely land on another node. At this point `kubectl proxy` will stop working for the dashboard.

(We should also consider relaxing/eliminating the network policy for the dashboard as this will break kubectl proxy completely once we support HA.)

/cc @bgeesaman @chuckha because of #115.

**Comment by jbeda** [comment]
Also /cc @mattmoyer.

**Comment by timothysc** [comment]
Somehow I totally forgot that we deployed this, and I don't know how I feel about that...
