### ISSUE TITLE
Where can I find etcd logs and it's endpoint

### ISSUE THREAD

**Issue by IshwarChandra** [heptio/aws-quickstart#168]
For some troubleshooting and a different use case I need to look into etcd log files.
I ssh into master node and go to /var/log but there is no etcd log files.
Also, I need to know etcd endpoint used by clients.
Please help

**Comment by chuckha** [comment]
@IshwarChandra The only client that uses etcd is the api server. It's run as a static pod so you'll find the logs using docker. If you ssh to the node and run `sudo docker ps` then `sudo docker logs <containerid>` You will see the logs for etcd.
