### ISSUE TITLE
Enable AuditLogs

### ISSUE THREAD

**Issue by chuckha** [heptio/aws-quickstart#170]
Use the kubeadm feature gate for audit logs. Perhaps something less verbose than "everything" but also everything would be interesting to have.

**Comment by timothysc** [comment]
/assign @detiber  

We should cross link with the wardroom issue too.

**Comment by timothysc** [comment]
I'm going to close this here, and we'll focus this change into wardroom.  

xref: https://github.com/heptiolabs/wardroom/issues/59
