### ISSUE TITLE
Trailing slash on S3 prefix isn't being added

### ISSUE THREAD

**Issue by krisdock** [heptio/aws-quickstart#174]
We have a customer issue where the Quick Start is failing with the following:

```
Error occurred during build: Failed to retrieve https://quickstart-reference.s3.amazonaws.com/heptio/latestscripts/awslogs.service: HTTP Error 403
```

We noticed the URL should be https://quickstart-reference.s3.amazonaws.com/heptio/latest/scripts/awslogs.service, so it appears the trailing slash that is supposed to be appended to the prefix isn't being appended.

```
The S3 key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slashes (/). It cannot start or end with forward slashes (/) because they are automatically appended.
```

This has happened with both the 'new VPC' and 'existing VPC' deployment options.

**Comment by krisdock** [comment]
The customer may have potentially been mucking with the default prefix. I asked them to add the trailing forward slash in the setup options (since the default entry actually has it) and the Quick Start deployed successfully.

**Comment by chuckha** [comment]
There's definitely something weird here... I was looking through all of our scripts and we *always* add the `/` and our comment on the field is weird...so I'll need to do a longer dig. Probably something like figure out why we say "never end with a trailing '/'" but then we default to something with a trailing /.
