### ISSUE TITLE
Ticket 148: Choose Subnets for new VPC template

### ISSUE THREAD

**Issue by rbankston** [heptio/aws-quickstart#183]
Would be great to be able to choose the subnet when creating a cluster with a new vpc. This would allow more folks to peer the cluster since they could be sure it didn't overlap with any existing vpc.

**Comment by detiber** [comment]
@rbankston can you elaborate a bit more on the use case that you see here? I would not expect overlapping of private subnet IP to matter between clusters since they would be communicating through the NAT gateway or through publicly exposed services/ingress.

**Comment by rbankston** [comment]
Sure can. In AWS when you want to establish a vpc peering session the cidr ranges on both sides of the peer have to be [unique](https://docs.aws.amazon.com/AmazonVPC/latest/PeeringGuide/vpc-peering-basics.html). It is similar to setting up a peer to peer vpn.
