### ISSUE TITLE
deploy-latest-published.sh file mentioned in README missing

### ISSUE THREAD

**Issue by nrb** [heptio/aws-quickstart#199]
The README links to https://github.com/heptio/aws-quickstart/blob/master/bin/deploy-latest-published.sh for getting a cluster via the command line. However, this file isn't in the repo. The output of ` git log --all --full-history -- bin/deploy-latest-published.sh` shows that it never existed.

What's the correct command or script to use?

**Comment by chuckha** [comment]
please use https://github.com/heptio/aws-quickstart/blob/master/bin/boot-latest-published.sh instead. I will fix the readme.
