### ISSUE TITLE
The creation process never completes within cloudformation

### ISSUE THREAD

**Issue by bwang221** [heptio/aws-quickstart#209]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
from: https://aws.amazon.com/quickstart/architecture/heptio-kubernetes/

choose 👍 
Deploy into a new VPC

follow the steps to fill in required information. then proceed with "Create".

**What did you expect to happen:**

I expected the VPC and Kubenetes cluster to be created.

The Nested stack completed as the status shows, but the master stack never completes, it shows "CREATE_IN_PROGRESS" forever.

The VPC is actually created, but if you check EKS service, no cluster is created, and no error messages in Cloudformation.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by timothysc** [comment]
"but if you check EKS service"...? 

This is not an EKS cluster.

**Comment by bwang221** [comment]
Interesting.

What I observed:

1. The master stack completed after 6 hours, while I expect it to complete in 10 minutes.
2. If I run the same template in couldformation in a region that does not support EKS, it fails quickly. If I run it in a region that supports EKS, it behaved as what I described.

I will run it again and let you know.
