### ISSUE TITLE
Missing cloud-provider integration

### ISSUE THREAD

**Issue by stevesloka** [heptio/aws-quickstart#214]
**What steps did you take and what happened:**

Deployed the quickstart to Ohio (us-east-2) and when I try and create a service type `LoadBalancer`, the external-ip stays `Pending`. Looking at the logs I see this:

```
WARNING: no cloud provider provided, services of type LoadBalancer will fail
```

I then tried deploying to Oregon (us-west-2) and have the same problem. 

**What did you expect to happen:**

When I create a service type LoadBalancer I get an ELB provisioned automatically.

**Comment by timothysc** [comment]
/assign @vincepri @chuckha  

This is weird, has something changed with cloud-provider integration?

**Comment by stevesloka** [comment]
Just to update, I rolled back the repo to `558b449` and it all seems to work fine. So something after that is the culprit either with the repo, or changes in how kubeadm works.

**Comment by craigtracey** [comment]
This appears to still be problematic.  Seems missing controller-manager config.
