### ISSUE TITLE
API Server Timeout when entering Admin Ingress Location

### ISSUE THREAD

**Issue by rbankston** [heptio/aws-quickstart#225]
**What steps did you take and what happened:**
Created an AWS Quickstart cluster and utilized the Admin Ingress Location IP address of my local isp to lock down access to the cluster.

The API ELB is locked down to *only* my admin ingress location but not any nodes for the cluster.

**What did you expect to happen:**
Cluster would be created and function properly without manual intervention.

**Anything else you would like to add:**
Was able to make the api elb work when adding the EIP of the vpc to the api security group.

- Kubernetes version: (use `kubectl version`):Kubernetes 1.11.1
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by rosskukulinski** [comment]
@rbankston could you please provide some additional details on how to reproduce this issue

**Comment by rbankston** [comment]
## Steps to Reproduce

1) Launch latest AWS-quickstart template from the Readme.
2) Proceed to fill out fields in the template as normal
3) In `Admin Ingress Location` enter your ip address if 1.2.3.4 was your ip address would be `1.2.3.4/32`
4) Launch quickstart

Quickstart will launch. The bastion host ingress location will be set properly to your local IP address. The load balancer for the control plane will be set to allow traffic from *only* 1.2.3.4/32 on ports 6443 and 443 sent to port 6443 of the control plane instance. The external control plane nat ip address isn't allowed to access the load balancer causing the cluster to fail creation.

**Comment by rosskukulinski** [comment]
@timothysc FYI - low priority, but definitely a bug we should probably fix.
