### ISSUE TITLE
Lasted launch link in README broken

### ISSUE THREAD

**Issue by jbeda** [heptio/aws-quickstart#252]
**What steps did you take and what happened:**
I clicked on the link on the readme called "Launch Latest Quickstart Now"

**What did you expect to happen:**
Launch into the latest version of the quickstart.  Instead, I get an error that says (confusingly) "Stack [template] does not exist" and "Stack with id template does not exist".  Not sure what is going on there.

**Comment by rosskukulinski** [comment]
Submitting a PR which I believe resolves the issue
