### ISSUE TITLE
RFE: Deeper logging integration(s) into AWS. 

### ISSUE THREAD

**Issue by timothysc** [heptio/aws-quickstart#46]
There are a number of options here depending on what a user is comfortable with.  

For the smaller scale, directing integrating into Amazon Cloud Watch makes sense. 
https://docs.docker.com/engine/admin/logging/awslogs/
http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html

For larger integrations or for folks who want it they could sub-template to stand-up AMZ-Elastic Search 
https://aws.amazon.com/elasticsearch-service/
namely: https://aws.amazon.com/about-aws/whats-new/2017/01/amazon-elasticsearch-service-free-tier-now-available-on-t2-small-elasticsearch-instances/ 

+ needs fluentd integration (link2)

**Comment by kensimon** [comment]
Closing, because we decided to document this for self-service instead: http://docs.heptio.com/content/tutorials/elastic.html
