### ISSUE TITLE
Write PRD for AWS QS

### ISSUE THREAD

**Issue by kstewart** [heptio/aws-quickstart#48]
Now that the Quick Start is live, we need to go back and appropriately scope the project. :-)

A PRD and/or design document needs to be written that captures the intended goal(s) for the QS. With that, we should be able to:

* Identify the overall feature set and create issues for each one
* Evaluate feature requests and determine if they fit the project vision

**Comment by kensimon** [comment]
Initial draft: https://github.com/heptio/aws-quickstart/issues/48

**Comment by kensimon** [comment]
Closing in favor of internally-tracked issue
