### ISSUE TITLE
Comparison to kube-aws etc. ?

### ISSUE THREAD

**Issue by hangtwenty** [heptio/aws-quickstart#60]
Hi there,

Any plan to break down differences from going with [kube-aws](https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html)? I'm new to Kubernetes and Kubernetes-on-AWS, coming from AWS ECS experience. I was happy to find your example (through the AWS blog), but then one of the first things I sought was a comparison table or other rationale about why not to build on that tool. Is it to be demonstrative, or for some other design choice?

I'm going to dig in and answer these questions for myself anyways — but thought I'd leave this issue in this persona, wondering this way, since you probably want to know how people receive this :-) So here's one case.

Cheers

**Comment by rdodev** [comment]
Hey @hangtwenty 

While we do not have a feature comparison table at the moment, the most important and crucial difference to keep in mind is that our quick start is meant as a way to get a kubernetes cluster up and running fast but not emphasizing on aspects that are *required* for a production-ready cluster (i.e. multi-master configuration, DR, security hardening -- other than what's recommended by AWS best practices -- and so forth), whereas the _aim_ of tools like kube-aws is to provide you with the options and facilities to bootstrap a production-ready cluster.

**Comment by hangtwenty** [comment]
OK, so someone like me could:

* Start with your quick start to tinker
* Once I grok some of it, start looking into `kube-aws` and `kops`, comparing and deciding what to proceed with?

Is that how you think of it?

**Comment by rdodev** [comment]
@hangtwenty 

That's definitely one of the aims of the quick start and a natural progression path  =)

**Comment by hangtwenty** [comment]
Thanks!
