### ISSUE TITLE
QuickStart Reference PDF Weave Links

### ISSUE THREAD

**Issue by christopherhein** [heptio/aws-quickstart#62]
Handful of Weave links in [heptio-kubernetes-on-the-aws-cloud.pdf](https://s3.amazonaws.com/quickstart-reference/heptio/latest/doc/heptio-kubernetes-on-the-aws-cloud.pdf) which need to be updated to the [Weave](https://github.com/weaveworks/weave) core repo.

- [ ] Page 4
- [ ] Page 8
- [ ] Page 14 
- [ ] Page 16
- [ ] Page 20

Thanks!

**Comment by kensimon** [comment]
Sorry, must have missed this when it came in.  We'll get that updated ASAP.

**Comment by kensimon** [comment]
PDF has been updated, thanks for reporting this.
