### ISSUE TITLE
Consider adding EC2 Spot Fleet / Spot ASG options

### ISSUE THREAD

**Issue by mattmoyer** [heptio/aws-quickstart#83]
Using spot instances could save a bunch of money for dev/test use cases.

**Comment by dasgoll** [comment]
Spot instances in dev would be awesome :)

**Comment by timothysc** [comment]
@chuckha please check over.

**Comment by timothysc** [comment]
I think I'm concerned about the UX and possible issues here.   

If folks are allowed to select spot instances it should be only for compute nodes and an opt-in behavior.

**Comment by timothysc** [comment]
We've updated image types in the last couple of iterations to allow a wider range.

**Comment by mattmoyer** [comment]
This issue is about using [Spot Fleet](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet.html) or other alternatives to regular ASG, not the EC2 instance types.
