### ISSUE TITLE
Error with "type: LoadBalancer" when deploying into existing VPC?

### ISSUE THREAD

**Issue by cguethle** [heptio/aws-quickstart#89]
I get the following deploying nginx ingress controller into a k8s cluster generated by your template (deploying into an existing VPC).

`Error creating load balancer (will retry): Failed to create load balancer for service nginx-ingress/nginx-ingress: could not find any suitable subnets for creating the ELB`

I suspect it is because the Public subnet that would be the recipient of the new ELB is not tagged appropriately and k8s doesn't have an available public subnet generated by the template before hand. Does that sound right?

**Comment by timothysc** [comment]
closing this in favor of #91 and there is a PR in flight.
