### ISSUE TITLE
LoadBalancerType changed to internet-facing from internal

### ISSUE THREAD

**Issue by danhartfiction** [heptio/aws-quickstart#91]
The CloudFormation template changed LoadBalancerType to force internet-facing.  This should be a configuration option to choose internet-facing or internal.  I am presently working on an update for this.

**Comment by danhartfiction** [comment]
I'm not sure what the AWS default is, however the CloudFormation template provided in this github hardcodes "internet-facing"  (See my pull request.)

I found this out by standing up this CloudFormation in my Dev account, and being unable to connect.  That is when I saw it was internet-facing, and thus not working with my network setup.

**Comment by chuckha** [comment]
Ah, yes, thanks for the clarification! Left one comment on the PR.

**Comment by chuckha** [comment]
Thanks for the patch!
